services:
  # Backend
  - type: web
    name: production-backend
    runtime: python
    buildCommand: ./backend/build.sh
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: production-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.10.3"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"

staticSites:
  # Frontend
  - name: production-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: production-backend
          property: host

databases:
  - name: production-db
    plan: free
